import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import localFont from "next/font/local";

const vangeda = localFont({
  src: [
    {
      path: "../../../public/fonts/Vangeda-Regular.ttf",
      style: "normal",
    },
    {
      path: "../../../public/fonts/Vangeda-Italic.ttf",
      style: "italic",
    },
  ],
  variable: "--font-vangeda",
});

const bricolage = localFont({
  src: [
    {
      path: "../../../public/fonts/BricolageGrotesque[opsz,wdth,wght].ttf",
      style: "normal",
    },
  ],
  variable: "--font-bricolage",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  return (
    <html lang="locale" className="scroll-smooth">
      <body className={`${vangeda.variable} ${bricolage.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
